version: "2"

services:
  nexus:
    container_name: nexus3
    image: sonatype/nexus3:3.37.0
    volumes:
      - "/mnt/d/nexus/data:/nexus-data"
    ports:
      - "8081:8081"
      - "8888:8888"
      - "8889:8889"
    ulimits:
      nofile:
        soft: "65536"
        hard: "65536"
    restart: always
