version: "2"

services:
  nexus:
    container_name: nexus3
    image: sonatype/nexus3:3.20.1
    volumes:
      - "/mnt/d/nexus/data:/nexus-data"
    ports:
      - "8081:8081"
      - "8888:8888"
      - "8889:8889"
    restart: always