#sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher
version: '2'

services:
  wekandb:
    image: rancher/rancher:v2.3.2
    container_name: rancher
    restart: always
    ports:
      - 8000:80
      - 8443:443