apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: wekan
  namespace: proxy
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
    - host: neobradley.me
      http:
        paths:
          - path: /wekan
            backend:
              serviceName: wekan
              servicePort: 9001