apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: wekan
  namespace: proxy
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: wekan.neobradley.me
      http:
        paths:
          - path: /
            backend:
              serviceName: wekan
              servicePort: 80