version: '3'
services:
  jenkins:
    image: jenkins/jenkins:2.176.1
    container_name: jenkins
    restart: always
    ports:
      - '9080:8080'
      - '59527:50000'
    volumes:
      - ./data/jenkins_home:/data/jenkins_home
# Update jenkins after running
# https://medium.com/@jimkang/how-to-start-a-new-jenkins-container-and-update-jenkins-with-docker-cf628aa495e9