version: '3.5'

services:
  redis:
    container_name: redis
    image: redis:6.2.0
    ports:
      - "6379:6379"
    networks:
      - kls-proxy
    restart: always

networks:
  kls-proxy:
    name: kls-net